apiVersion: v1
kind: Secret
metadata:
  name: conn-secrets
type: Opaque
stringData:
  DATABASE_URI: postgres://postgres:postgres@postgres-svc.default.svc.cluster.local/orders?sslmode=disable&connect_timeout=5
  RABBITMQ_URI: amqp://guest:guest@rabbitmq-svc.default.svc.cluster.local:5672/